### ISSUE TITLE
Support for specific versions of plan

### ISSUE THREAD

**Issue by kaspernissen** [lunarway/shuttle#16]
We need to support using a specific version of a plan. 

It could be a specific git commit, git tag or similar.

**Comment by emilingerslev** [comment]
Yeah, it would be awesome to able to lock to a specific tag or commit with fx a `shuttle.lock` file containing the commit. That way we would have the latest when you specify `https://github.com/lunarway/shuttle-example-go-plan.git` as your plan, but I would require a `shuttle upgrade` to get the latest version of the plan.

**Comment by emilingerslev** [comment]
It would nice to point to a branch of a plan too

**Comment by Crevil** [comment]
I first iteration of this could be the branch support instead of specific versioning, as this solves most of our problems when changing plans.
We find the automatic "latest" concept of plans powerfull to speed change rollout, but the problem with this approach is clear when testing out new things in the plans and breaking things for every user of the plan.

If we support branches, we can point a project over to a new feature branch of the plan and test out stuff and when ready to deploy to every one, merge it into `master`.

**Comment by Crevil** [comment]
Is implemented in #35
